### ISSUE TITLE
readLinePrivate() ignores sensor 0 and wastes information.

### ISSUE THREAD

**Issue by drf5n** [pololu/qtr-sensors-arduino#15]
In [readLinePrivate](https://github.com/pololu/qtr-sensors-arduino/blob/4a0d1c59842307164735f923f0eb99cbb2538428/QTRSensors.cpp#L656C1-L670C4) Since i=0 for the first sensor, it is always ignored in the weighted average:

```
  for (uint8_t i = 0; i < _sensorCount; i++)
  {
    uint16_t value = sensorValues[i];
    if (invertReadings) { value = 1000 - value; }


    // keep track of whether we see the line at all
    if (value > 200) { onLine = true; }


    // only average in values that are above a noise threshold
    if (value > 50)
    {
      avg += (uint32_t)value * (i * 1000);
      sum += value;
    }
  }
```

It wastes a sensor and its information to weight it by zero.  You could start with i=1 to use the sensor information, but that solution would break all the code that was already using this library.

Wasting the information is less of a concern with the larger sensors, but for the smaller ones, it discards 1/N of the information.  That's 50% for a 2-sensor device, 33% for a 3 sensor, etc..  If the line is fully under sensor 0, the code will return the same 0 as if it were off the line.

**Comment by kevin-pololu** [comment]
This is the same topic raised in #14: it's true that the 0th element contributes 0 to `avg`, but it still affects the result because it changes `sum`.

For example, if you have a 2-sensor array, sensor 0 reads 200, and sensor 1 reads 500:
`avg` = 200 * 0 + 500 * 1000 = 500000
`sum` = 200 + 500 = 700
`_lastPosition` = `avg` / `sum` = 714

If sensor 0 reads 800 instead:
`avg` = 800 * 0 + 500 * 1000 = 500000
`sum` = 800 + 500 = 1300
`_lastPosition` = `avg` / `sum` = 384

**Comment by drf5n** [comment]
I understand.  In real systems you likely always have some level of signal from sensor 1 to weight against sensor 0.  My concern comes from about interpreting the return values, and a value of "0" doesn't distinguish between no signal and a strong signal from sensor 0.   In the ideal case where sensor 0 is the only one with a contribution, and the math produces a result indistinguishable from no signal.  I see that the code has a couple workarounds to avoid a potential divide by zero.

No worries.
Thanks.

**Comment by kevin-pololu** [comment]
The `readLine` functions remember where they last saw the line and return 0 or the max value if the sensors lose track of it (in the hopes that the robot will find the line again if it keeps turning in that direction), so these functions will actually mask a situation with no signal by design. If you are interested in detecting that situation, it's better to look at the individual readings yourself; the values are stored in the `sensorValues` array that you pass to the function.
